version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: exercises
      POSTGRES_USER: root
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - postgres_exercises_data:/var/lib/postgresql/data

volumes:
  postgres_exercises_data:
